---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mymind-discord-bot
  namespace: mymindinai
  labels:
    app: mymind-discord-bot
spec:
  replicas: 1
  strategy:
    type: recreate
  selector:
    matchLabels:
      app: mymind-discord-bot
  template:
    metadata:
      labels:
        app: mymind-discord-bot
    spec:
      containers:
      - name: discord-bot
        image: jgilfoil/mymindinai-discordbot:latest
        env:
        - name: DISCORD_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: discordbot-secrets
              key: DISCORD_BOT_TOKEN
        - name: MIDJOURNEY_BOT_ID
          valueFrom:
            secretKeyRef:
              name: discordbot-secrets
              key: MIDJOURNEY_BOT_ID
        volumeMounts:
          - mountPath: /app/images
            name: images
      volumes:
      - name: images
        persistentVolumeClaim:
          claimName: mymindinai-images-nfs
