---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vector-aggregator
  namespace: observability
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://helm.vector.dev
      chart: vector-aggregator
      version: 0.20.0
      sourceRef:
        kind: HelmRepository
        name: vector-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  dependsOn:
    - name: loki
      namespace: observability
  values:
    role: Stateless-Aggregator
    image:
      repository: timberio/vector
      tag: 0.20.0-debian
    customConfig:
      data_dir: /vector-data-dir
      api:
        enabled: false
      # Sources
      sources:
        journal_logs:
          address: 0.0.0.0:6000
          type: vector
          version: "2"
        kubernetes_logs:
          address: 0.0.0.0:6010
          type: vector
          version: "2"
      sinks:
        loki_journal:
          type: loki
          inputs:
            - journal_logs
          endpoint: http://loki:3100
          encoding:
            codec: json
          batch:
            max_bytes: 2049000
          out_of_order_action: rewrite_timestamp
          remove_label_fields: true
          remove_timestamp: true
          labels:
            hostname: >-
              {{`{{ host }}`}}
        loki_kubernetes:
          type: loki
          inputs:
            - kubernetes_logs
          endpoint: http://loki:3100
          encoding:
            codec: json
          batch:
            max_bytes: 2049000
          out_of_order_action: rewrite_timestamp
          remove_label_fields: true
          remove_timestamp: true
          labels:
            app: >-
              {{`{{ kubernetes.pod_labels.app\.kubernetes\.io/name }}`}}
            container: >-
              {{`{{ kubernetes.container_name }}`}}
            namespace: >-
              {{`{{ kubernetes.pod_namespace }}`}}
            node: >-
              {{`{{ kubernetes.pod_node_name }}`}}
            pod: >-
              {{`{{ kubernetes.pod_name }}`}}
    podMonitor:
      enabled: true
    service:
      enabled: true
      type: LoadBalancer
