---
apiVersion: v1
kind: Pod
metadata:
  name: "restic-shell"
  namespace: "media"
spec:
  restartPolicy: OnFailure
  containers:
  - name: list
    image: docker.io/restic/restic:0.15.1
    command: ["/bin/sh", "-c", "while true; do sleep 99999; done"]
    envFrom:
    - secretRef:
        name: "transmission-downloads-restic-secret"
