---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: discord-flux-info
  namespace: flux-system
spec:
  type: discord
  username: flux
  channel: cluster-info
  secretRef:
    name: discord-flux-info-webhook-url
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: k3s-cluster-info
  namespace: flux-system
spec:
  providerRef:
    name: discord-flux-info
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: "*"
    - kind: Kustomization
      name: "*"
    - kind: HelmRepository
      name: "*"
    - kind: HelmRelease
      name: "*"
  suspend: false

---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: discord-flux-alerts
  namespace: flux-system
spec:
  type: discord
  username: flux
  channel: cluster-alerts
  secretRef:
    name: discord-flux-alerts-webhook-url
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: k3s-cluster-alerts
  namespace: flux-system
spec:
  providerRef:
    name: discord-flux-alerts
  eventSeverity: error
  eventSources:
    - kind: GitRepository
      name: "*"
    - kind: Kustomization
      name: "*"
    - kind: HelmRepository
      name: "*"
    - kind: HelmRelease
      name: "*"
  exclusionList:
    - "error.*lookup github\\.com"
    - "waiting.*socket"
  suspend: false
