# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: discord-flux-alerts-webhook-url
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:veAgdgdUy361+ziS4H8vXdxlzFp/LbwVF0Vuw4nXjFo4GxLkNdlj+kM3QC3yVylSsAF5Hh3UNTAv4FicbRKT3MWMbtO+Tg6H1f9jKoLBtn4GGParM65A5UxqZPNahvOL34eDxqs6kQOBLIIUKRc+2yUVqL/5xO9o,iv:Mkk6bSjJdjqgNouo+BtyfhntHk5P251LEMXubR81/rY=,tag:cLL+YVwD5D0fIAFWhpS8NA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-09-19T18:49:16Z"
    mac: ENC[AES256_GCM,data:mnT0uBnsjE1peKcaPWiwhHTDEZxXqrbHTP5FoQ6vsOXxCq9aQRc0gbePv4580DOcCtMBOPphKIcBgSGpwxGgEl5eZYM6NKhb+d6v/cRzdSVoh4CTbNmqGlPJ3KRfyaOtZ0/yid9XpFAw+XmG9nYwBja8ePFuRfZ9Gidw8Ol+Phw=,iv:4V3mfUiGcB4aylUajw5nMvyXOgCg3trxPN24OgkNat4=,tag:/oW3xV2+1P7diAeo+m3tlg==,type:str]
    pgp:
        - created_at: "2021-09-19T18:49:15Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/+NhdxSsFPOAQ//aDYFWXA/7Iid3mDLqExVspb5dcaJTFhNOaIgAwHjsmoN
            NdgdKuQEOcrOgFWgzmSVkTYiHOo+MGE0TWXCFwL/Zq3KmUIBTfk1pukpJ1Weqmdk
            U5X1vIQUOeHRtSK3AwxVi8w0vqlDj+HeNLlpWnLpZMX4PR60DB5pmcIloGP7RpFF
            F23h8Z/no+c4sLcF+FMN1cKDm/SVshYsOP/aPwqJa42TCXCfZPIUPwc391QpdYF+
            pJxz2RlTqDPC98oChLs7u4/vzEQlyn8vaym/nLnhlzK0G4toqLBAiRJ16yT2+F7z
            s3d7Byx4Sqmw1PIrPkMojRS+Ebc7dfFpQh1QmgF9OOP79oIxa/wumqf5cfq5SKcC
            eWK463nXd+CwdX3aITFtsePjJ9rx8giavWmNJrIQxtkPMs1sF+yKu8yMt+MCt2jn
            MgfRKOvhewM9Oz0eozq3ueNCUUWlA4LBvxhFVIiVAVuKyqyV2gJWEFRlvAJ/7z5Y
            wfIIBvzRFDsolbJWUEOPJ/1msJ+ZWHz7EGrWl4HohSF/1RsKZjEUYAne04XP7VgI
            NIELZPxA2u20RF5ivfdLLfsgMmgAEgQNGJpO/xbkL+oV7LpzvW60qVn4ERRIP64+
            TA01qd5hrzRJfHS/lOmn6B7DIP35OOAbbA779jSHjK9RfAWZhgxQRjNBKC7lPMnS
            XgEy8Clk6SxcNqHzwLQSMvgbuRPQwsftMxEIBfGOvD6PEp2xM/N6NkT4mPPht0hB
            +ZdG0tuWM3VI8VbidL0v19namxgJL6o2IkSFYW2c5aBUH8gd/+yhXriSIgz9TBw=
            =atq6
            -----END PGP MESSAGE-----
          fp: EF57649CB133800963D136C6B813D6D7F00C2572
        - created_at: "2021-09-19T18:49:15Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAy4XleZm/m5jAQ/+MalCGG8czL//b3lU0IHrAO25Rd7ru+8LYfofJanDt2NW
            TE+3eBwxKrIzM7HX/zATobvoCBsjtaraRkadEu4ylVVpl/e1RejlZUJCHGFoZlq6
            Cba0oPrHeYJp35ydhfQQDJXRBIiQCi8EyPWASfNrtr8NLv5yafBmnSnXcFPlIbAF
            OWTXXOOKI6AMhXXv7Sy+Tuvv3+yR5yCmOTq3HdQgxPLpCdizqjxpeLi9nKvYS6Fs
            mc1dq99Tzz3g+nNDBP2j1/tQKe66P/5UCG+nCvGI6A/Bp4YeA6ZuBMH6XOuDo0T0
            1py+lr0Kn4+e7xO6ECF359MoIVH5Um8IJNdTETDvhogEimiw5uwVPDpnxRCiyypv
            TAvqQYs2RCvwx/Ie3W8oxjUVMJBuyOYeg+UtNp/hWKM/RfoDdleiALK2uiS8m3tP
            0Uk62IvQrvBPNHnBOqrryJt+lbrRq5bB7lKmD2H0tsriN+yoHd9EVIkYXS8jz4Lm
            G4m6m4cTNyzODl4DA0sTu8dGLHW0IPjQgAFZrkGhQ+j14Fw8M2u9sQlyjBsbmnR2
            1cPeBMeED5vfq797yIAluQjMw3ZsGRVWJhTETDD36M72R5+Z/XTu2NXMCAMcPwGT
            Qyy2bPQ9ZJ9rEZogyH/SpQuMHK2SIxWbQLCwOqzS+L+45oYrIxK8LM7+Qvqx4iDS
            XgEclOdTsxe9aHbcfTOZtkyh8WOzrn26niam1rNZwzfeEmM7Hi0yObSP07dAfEJG
            79JGN1PwbTa/AheQVzvIJBeNp4nCsAdRxVE784Gv66Qfw9bqza/NYqCE+N4YmsE=
            =zY/H
            -----END PGP MESSAGE-----
          fp: 0341B76EFD798D9008EE3A5B442753990A538576
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
