apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- bitnami-charts.yaml
- ingress-nginx-charts.yaml
- jetstack-charts.yaml
- k8s-at-home-charts.yaml
- metallb-charts.yaml
- traefik-charts.yaml
- rook-ceph-charts.yaml
- weaveworks-kured-charts.yaml
- vmware-tanzu-charts.yaml
- node-feature-discovery-charts.yaml
- grafana-charts.yaml
- vector-charts.yaml
- bjw-s-charts.yaml
