---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rabbitmq-operator
  namespace: worklab
spec:
  interval: 5m
  chart:
    spec:
      chart: rabbitmq-cluster-operator
      version: 2.6.8
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  values:
    global:
      storageClass: "ceph-block"

    clusterOperator:
      image:
        registry: docker.io
        repository: bitnami/rabbitmq-cluster-operator
        tag: 1.13.1-scratch-r2
        pullPolicy: IfNotPresent
      resources:
        limits:
          cpu: "1000m"
          memory: "2Gi"
      podLabels: {}
      podAnnotations: {}

    msgTopologyOperator:
      image:
        registry: docker.io
        repository: bitnami/rmq-messaging-topology-operator
        tag: 1.7.0-scratch-r0
        pullPolicy: latest
      resources:
        limits:
          cpu: "1000m"
          memory: "2Gi"
      podLabels: {}
      podAnnotations: {}
      service:
        type: LoadBalancer
        loadBalancerIP: ""
        externalTrafficPolicy: Cluster
        annotations: {}
    useCertManager: false
