---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rook-direct-mount
  namespace: rook-ceph # namespace:cluster
  labels:
    app: rook-direct-mount
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rook-direct-mount
  template:
    metadata:
      labels:
        app: rook-direct-mount
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: rook-direct-mount
          image: rook/ceph:v1.10.12
          command: ["/bin/bash"]
          args: ["-m", "-c", "/usr/local/bin/toolbox.sh"]
          imagePullPolicy: IfNotPresent
          tty: true
          env:
            - name: ROOK_CEPH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: rook-ceph-mon
                  key: ceph-username
            - name: ROOK_CEPH_SECRET
              valueFrom:
                secretKeyRef:
                  name: rook-ceph-mon
                  key: ceph-secret
          securityContext:
            privileged: true
            runAsUser: 0
          volumeMounts:
            - mountPath: /dev
              name: dev
            - mountPath: /sys/bus
              name: sysbus
            - mountPath: /lib/modules
              name: libmodules
            - name: mon-endpoint-volume
              mountPath: /etc/rook
            - name: nas-media-data
              mountPath: /mnt/nas-media-data
            - name: nas-backup-data
              mountPath: /mnt/nas-backup-data
            - name: nas-downloads-data
              mountPath: /mnt/nas-downloads-data
            - name: direct-mount-scripts
              mountPath: /scripts
      # if hostNetwork: false, the "rbd map" command hangs, see https://github.com/rook/rook/issues/2021
      hostNetwork: true
      volumes:
        - name: dev
          hostPath:
            path: /dev
        - name: sysbus
          hostPath:
            path: /sys/bus
        - name: libmodules
          hostPath:
            path: /lib/modules
        - name: mon-endpoint-volume
          configMap:
            name: rook-ceph-mon-endpoints
            items:
              - key: data
                path: mon-endpoints
        - name: nas-media-data
          nfs:
            server: "${NAS_ADDR}"
            path: /volume2/Media
        - name: nas-backup-data
          nfs:
            server: "${NAS_ADDR}"
            path: /volume1/Backup
        - name: nas-downloads-data
          nfs:
            server: "${NAS_ADDR}"
            path: /volume9/downloads
        - name: direct-mount-scripts
          projected:
            defaultMode: 0775
            sources:
              - configMap:
                  name: direct-mount-scripts
