---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homer
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: homer
      version: 6.0.1
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
  values:
    image:
      repository: b4bz/homer
      tag: 21.07.1
      pullPolicy: IfNotPresent
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
        - host: "homer.${SECRET_DOMAIN}"
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - "homer.${SECRET_DOMAIN}"
    persistence:
      config:
        enabled: true
        existingClaim: homer-config
        mountPath: /www/assets
    configmap:
      enabled: true
      config: |
        ---
        # Homepage configuration
        # See https://fontawesome.com/icons for icons options
        
        title: "Home Cluster Dashboard"
        subtitle: "Kubernetes Cluster"
        logo: "logo.png"
        # icon: "fas fa-skull-crossbones" # Optional icon
        
        header: true
        footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.
        
        # Optional theme customization
        theme: default
        colors:
          light:
            highlight-primary: "#3367d6"
            highlight-secondary: "#4285f4"
            highlight-hover: "#5a95f5"
            background: "#f5f5f5"
            card-background: "#ffffff"
            text: "#363636"
            text-header: "#ffffff"
            text-title: "#303030"
            text-subtitle: "#424242"
            card-shadow: rgba(0, 0, 0, 0.1)
            link-hover: "#363636"
          dark:
            highlight-primary: "#3367d6"
            highlight-secondary: "#4285f4"
            highlight-hover: "#5a95f5"
            background: "#131313"
            card-background: "#2b2b2b"
            text: "#eaeaea"
            text-header: "#ffffff"
            text-title: "#fafafa"
            text-subtitle: "#f5f5f5"
            card-shadow: rgba(0, 0, 0, 0.4)
            link-hover: "#ffdd57"
        
        # Optional message
        message:
          #url: https://b4bz.io
          style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
          title: "Service List"
          icon: "fa fa-grin"
          content: "This is a list of all services available in our home. <br /> Find more information on <a href='https://github.com/jgilfoil/k8s-gitops'>github.com/jgilfoil/k8s-gitops</a>"
        
        # Optional navbar
        # links: [] # Allows for navbar (dark mode, layout, and search) without any links
        links:
          - name: "Contribute"
            icon: "fab fa-github"
            url: "https://github.com/bastienwirtz/homer"
            target: "_blank" # optional html a tag target attribute
          - name: "Wiki"
            icon: "fas fa-book"
            url: "https://www.wikipedia.org/"
        
        # Services
        # First level array represent a group.
        # Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
        services:
          - name: "Media"
            icon: "fas fa-photo-video"
            items:
              - name: "Plex"
                #icon: fas fa-compact-disc
                logo: "https://raw.githubusercontent.com/NX211/homer-icons/7e25ff430c87accb39b8b39ddb2e9617f46d6fb1/png/plex.png"
                subtitle: "Movies, TV, and Audio Books"
                tag: "App"
                url: "https://plex.apostoli.pw:32400/web"
                target: "_plex" # optional html a tag target attribute
              - name: "Medusa"
                logo: "https://raw.githubusercontent.com/NX211/homer-icons/master/png/medusa.png"
                subtitle: "TV Manager"
                tag: "App"
                url: "http://192.168.1.10/medusa/home/"
              - name: "Transmission"
                logo: "https://raw.githubusercontent.com/NX211/homer-icons/master/png/transmission.png"
                subtitle: "Media Aquisition"
                tag: "App"
                url: "https://192.168.99.50/transmission"
              - name: "Deluge"
                logo: "https://raw.githubusercontent.com/NX211/homer-icons/master/png/deluge.png"
                subtitle: "Media Aquisition"
                tag: "App"
                url: "http://192.168.99.50:8112"
          - name: "Infra Tools"
            icon: "fas fa-tools"
            items:
              - name: "Ceph"
                logo: "https://raw.githubusercontent.com/NX211/homer-icons/master/png/rook.png"
                subtitle: "Rook-Ceph Storage Cluster Dashboard"
                tag: "Tools"
                url: "https://rook.apostoli.pw"
              - name: "NAS"
                logo: "https://raw.githubusercontent.com/NX211/homer-icons/master/png/synology.png"
                subtitle: "Synology NAS Dashboard"
                tag: "Tools"
                url: "https://wanshitong.apostoli.pw:5001"
              - name: "Traefik"
                logo: "https://raw.githubusercontent.com/NX211/homer-icons/master/png/traefik.png"
                subtitle: "K8s Ingress and Traffic Router"
                tag: "Tools"
                url: "https://traefik.apostoli.pw"
              
