---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: plex
  namespace: media
spec:
  sourcePVC: plex-config-v1
  trigger:
    schedule: "15 11 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 10
    repository: plex-restic-secret
    cacheCapacity: 5Gi
    volumeSnapshotClassName: csi-ceph-blockpool
    storageClassName: ceph-block
    retain:
      daily: 10
      within: 3d
