# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: plex-restic-secret
    namespace: media
type: Opaque
stringData:
    RESTIC_REPOSITORY: ${RESTIC_REPOSITORY_URL}/volsync/media/plex
    RESTIC_PASSWORD: ${RESTIC_REPOSITORY_ENCRYPTION_KEY}
    AWS_ACCESS_KEY_ID: ${RESTIC_AWS_ACCESS_KEY_ID}
    AWS_SECRET_ACCESS_KEY: ${RESTIC_AWS_SECRET_ACCESS_KEY}
