---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: overseerr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 1.1.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  install:
    createNamespace: true
  values:
    image:
      repository: ghcr.io/sct/overseerr
      tag: 1.30.1
    env:
      TZ: "America/New_York"
      LOG_LEVEL: "info"
      PORT: 80
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "overseerr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "overseerr.${SECRET_DOMAIN}"
            secretName: "overseerr-tls"
    persistence:
      config:
        enabled: true
        existingClaim: overseerr-config-v1
        mountPath: /app/config
    resources:
      requests:
        memory: 250Mi
        cpu: 100m
      limits:
        memory: 750Mi
    podAnnotations:
      backup.velero.io/backup-volumes: config
