---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: radarr
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      chart: radarr
      version: 16.2.3
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    image:
      repository: ghcr.io/k8s-at-home/radarr
      tag: v4.1.0.6175
    env:
      TZ: "America/New_York"
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "radarr.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "radarr.${SECRET_DOMAIN}"
            secretName: "radarr-tls"
    podSecurityContext:
      supplementalGroups:
        - 100
    metrics:
      enabled: false
    persistence:
      config:
        enabled: true
        existingClaim: radarr-config-v1
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS_ADDR}"
            path: /volume2/Media
        mountPath: /media
      downloads:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS_ADDR}"
            path: /volume9/downloads
        mountPath: /downloads
      scripts:
        enabled: true
        type: configMap
        name: reverse-symlink-radarr
        defaultMode: 0777
    resources:
      requests:
        memory: 250Mi
        cpu: 100m
      limits:
        memory: 2000Mi
    podAnnotations:
      backup.velero.io/backup-volumes: config
      setGateway: "true"
