# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:/BMzXHPwAbxalYY=,iv:Ikm0bSKot3USGy/5ROwKkHcY162bQv891BVrcIIax+s=,tag:leVbTMmKKrTRZHh3Qz1wnw==,type:str]
    SECRET_CLOUDDNS_EMAIL: ENC[AES256_GCM,data:j6WLNd5tckg/R4XSE4UbIG2B,iv:Wp/fgI5GGoKtVyuP9Qhqe85wQVcJ7UAuWn2G8n76wvI=,tag:8107copfeD4UpCDgUpVdVw==,type:str]
    SECRET_CLOUDDNS_PROJECT: ENC[AES256_GCM,data:V9saLfyaghE9AaMN,iv:8VGCG6kNVblbxM/sIpJqk6i7H4OMV7pNIXSoCJc0Mhk=,tag:4vdPmJ5GbTYp2gDJWu6x9A==,type:str]
    SECRET_KURED_DISCORD_WEBHOOK: ENC[AES256_GCM,data:gn26nDQJZmbjL3bYWWLOeOQ4ZoQWJHR3ygRvh1lfs7opP0mBXKkxktPwfY9yyGeOTOQs+roSArelZDFPZH6/EHxmC0sWgvNBb4ITKCW3xCTrykrsrIpUCZhUcY3FPxo8Mg==,iv:JF6CkXTMKYpfTCsKHBjZKDSBJp9Xx6lTkWoNaqosawY=,tag:DSGSwqCpEd//LASyNDg5OQ==,type:str]
    SECRET_TRANSMISSION_RPC_PASSWORD: ENC[AES256_GCM,data:0XBoWS2dvOJP/3j9eEzBxg==,iv:iF/K1Eq6q2jNjlaOMUj+9pF8oE65wDl2TK7WdsMiNC0=,tag:uys3vlZln16I5sKaI30nQg==,type:str]
    SECRET_MINIO_LOKI_ACCESS_KEY: ENC[AES256_GCM,data:9ekw7xLmCUAdRAGG,iv:lzVvgb7w8B+JodXbjzkPTllaoQHpfaMFPksHiRoZnSA=,tag:yf2BQfGzjtRZHwhkU9QAOA==,type:str]
    SECRET_MINIO_LOKI_SECRET_KEY: ENC[AES256_GCM,data:p4Epye/PHjxWP1tAdDiW5XWk0n7U08I=,iv:4UiodC8xT1V5ioR7ErFOoZ7y+qCutIEpEA7yvqJaqnU=,tag:lCn8u3p9RlTPlm5QosNgIg==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:vtkOuQIU6D3P6nz2bJp1LQ==,iv:YYm2CdUT30BLxB+akm7qm+RITrTOIy4hS9eh3NFDv/w=,tag:O6w7vQ8cCDJ1PaytzQHzxw==,type:str]
    SECRET_VPN_GATEWAY_PORT: ENC[AES256_GCM,data:1vp+WA==,iv:+s6kNH6IYcE46ln3er7SE7Qp9FUc/6zLBs1O2PFMsdk=,tag:B1aGwT06PaSNDQhdK5wtDQ==,type:str]
    RESTIC_REPOSITORY_URL: ENC[AES256_GCM,data:b4gcRjBcYMyl8bPOWyTy22O3JfzEz6eIeas4+Q3ZIeAr0z/YySm9qzZeXcHP6Q==,iv:kVW4lu+1sCODX0olBWwd4RiLOQSouzcMHdJ6IdbujWQ=,tag:E3EhuUxVn/QW8nuuUkZ60g==,type:str]
    RESTIC_REPOSITORY_ENCRYPTION_KEY: ENC[AES256_GCM,data:nxlt03teg7Znm4wJJaeffA==,iv:IKPWdCmTC29TGMU+tGPG+WWGqaijLGLR3BEHzhrLIJo=,tag:K3B99HzY3QzAS/EHrZ3lhw==,type:str]
    RESTIC_AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:3SuhuY0O/thvdVOru49AoQ==,iv:gIDenSrN4Ihk7Yc4wXlO717kLK9ii+jpdrHLc9IC3kU=,tag:rQbGApx8uK0aNyvtKuIadQ==,type:str]
    RESTIC_AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:Ca5UV/TSYCuBUHLaUGEjBAWWWYowxX916jqSjl+nVTM=,iv:9wUlX2V8ias+hcy3HgorC+b2e0CkQLW+yHOBOKzFMeU=,tag:2tMfabA34h1dcitzI0LgpQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ktk92hs2qmfm8wnchvjve4z3wx60csm8g37mqj5gaw480x6mvemsn3rd4p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2NXBWa0p4ak9MeEo0SUtV
            bFNWUWs1eks2cGpLeVlBb2F0c256OEZhc1ZzClhrMEVFVURFRFBzc1pkUWIvSmdV
            bmxBa1liRjZrMk5TZThIWjdjZ1dPVkEKLS0tIDNFakpYZHBuWXpnVUV2emJ4Vldl
            OWV0dWpxSVQ0Mm1XcWFDbFo3OVQ4am8KZ/dBFfiJIAQ62heLQtNBOelt+2y5FoAg
            XSXC3o18OCkgVRi6ZEwHs1huQItMLfMvk/L4I0zYC2A3H/dy8Jz7nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-17T20:58:17Z"
    mac: ENC[AES256_GCM,data:fWBCIBP51YBeUeSJXwz1QGQjlgnh8tIZImGIgyIzlhl6L6b20C0wcWC7bwmScKLAMrNpZzPS45I4lXd1ySc1jgpd97uGAgyqJaEtAXozmPQ5i1554wtp/P/EPQrw8tQSUSy9RcaSzklU4XzATowUcoV+5w5uTI7sa2nkZN8LFgo=,iv:eDiu57XYrJ/nZB+TfqfNcBkSgnEU1E0JYbAJtsuKYro=,tag:biUc71Oh571pFyBwuSPc9A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
