# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:DhdfQRWUWt8uEo0=,iv:108xTFPfmBzdTyHsOdQFm7iHh0HtJU3SY8CB0sQMQwQ=,tag:3GS1v4E9LGGP2YQ/wyEjig==,type:str]
    SECRET_CLOUDDNS_EMAIL: ENC[AES256_GCM,data:VphU0C3v+3+AM06AiJs0rkiX,iv:Vltm08eizfCFCwODRpNRrx2YiNRHZSBUPAeRWppR67g=,tag:AXacynLFIKUrix3ZOmyc6g==,type:str]
    SECRET_CLOUDDNS_PROJECT: ENC[AES256_GCM,data:pg5hY7aUPAGwWLJO,iv:UOnHPX4cpF1ivYI6JOY0Xn+BI5VIU45xGSKpNcGu/To=,tag:19ZOO+FORtNjL6Yr4ItBZw==,type:str]
    SECRET_KURED_DISCORD_WEBHOOK: ENC[AES256_GCM,data:sjm744qmiJ/euSCj4djV2eYDh8sSMkIfVqzDmAzAEDOMfUoyZ8Pjp1I/G8x7FThz+fTwRdDCwHQZkrcUMmKoTUGPF9OK/Y+3Qt1VsVggy9wZKQHYTETsIW56mRle0xObhA==,iv:PMqgNVboaH7sGZbncOB2O9xfNgFGg9OL7+tKSdO0Qe0=,tag:wIpjOA9sfS7OTjQ27JB3qA==,type:str]
    SECRET_TRANSMISSION_RPC_PASSWORD: ENC[AES256_GCM,data:9HjTyvbwELn3nDHcTigd+g==,iv:JFa+2xxvDkUqC9PHHS3uY5RBNTaoyxciLf08wZ9TAQ0=,tag:CU41UNW5Wwiz96ewqeYXLA==,type:str]
    SECRET_MINIO_LOKI_ACCESS_KEY: ENC[AES256_GCM,data:qISTTaNLkzbxOSjN,iv:TRt10e1hQbXD/ssEF1odOOsDOnW9UwHOe/JEv4eCO20=,tag:lZ2kwjFMnLsWrSQEBE+0lQ==,type:str]
    SECRET_MINIO_LOKI_SECRET_KEY: ENC[AES256_GCM,data:OfaZAxZdRm4LtXuUGiQk8/df5cLMc04=,iv:pA6jrJ1IzalBrmxfVW/EkHPG4hT2dnv3lUdLiYN4iCI=,tag:kYmQh9uvSPccX9H1+Lvcyw==,type:str]
    SECRET_GRAFANA_PASSWORD: ENC[AES256_GCM,data:XlpZQ55FtiZCXm2zbfGWkg==,iv:cQraNTRENBm+cWLdJYGzR+KMcgBdB6Q07U7LdDZ0OQM=,tag:KSyofsBkyN+b91gdwrQ2Hw==,type:str]
    SECRET_VPN_GATEWAY_PORT: ENC[AES256_GCM,data:+X1sNQ==,iv:YV4fb6Y6Ns96dQ2b6wGE+bFllOBziyn+70vaJcaB3sA=,tag:Uczr6L3BP4m9ZrU0fxG2dw==,type:str]
    RESTIC_REPOSITORY_URL: ENC[AES256_GCM,data:Cz+pdr0aXKXzKNDYegk5KK6XAK/gU+b8UIfgwtqRzKP9wPcULqtsyGQSpFgfkw==,iv:eod31QJaWt3pz8G2JD2HJadvVEB/r0/i8VhRLijhxH0=,tag:n49QMgi5npnvyekoEXQYzA==,type:str]
    RESTIC_REPOSITORY_ENCRYPTION_KEY: ENC[AES256_GCM,data:Dwso2nhop7SKDDVPVVTIcQ==,iv:MRzMU+SQAlNThFloMdO8b6uptKAGCMqaBYZ2NoYtmu8=,tag:xa/RYwjBhYz7+gxp1Ox8aw==,type:str]
    RESTIC_AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:40XtE1F0VSgn4YNzTIWtHg==,iv:dCbEoprOTSnO7u20h9vtZxcj4yZPTaUJhe7ezF1HM/Q=,tag:GITb4vlFZRB1muMhgcS/NQ==,type:str]
    RESTIC_AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:K4Ep5sbBI8sfLEqrtwr8hcgfIa4kfsMpsIVYVzJTLzQ=,iv:7q3l9yWck364jxIWrpExYKfP17bRNlWWadIscNIuAwg=,tag:af3eKDu23iAsksQ5l8Wlww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-01-17T01:27:18Z"
    mac: ENC[AES256_GCM,data:kh5dDyAOBc//dCDxiLtHBhA12QWYisDDnOwIJcN7BdjBHjcoOOQKMgJKBpxY+PB5n0jlFqWcSVyDtC+HQ/3yEypwPxWxg2R4LWko6scDzDkkeAsIY6R14cZRNkt38ea0mWcGZ22HnZ2qU8ZeisRLuabwxrz2x/M86UzYWiEbRrk=,iv:TaiCktUCw8QD5z8ZdiJAvSWNOnO+gIKtJN2gDUaXJuQ=,tag:oT1iSxXCPG0hJC6EdXugHw==,type:str]
    pgp:
        - created_at: "2023-01-17T01:27:17Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA/+NhdxSsFPOARAAm8vsub0zYmx3Ujx7yMMzUmpUOJkKvPljBKZ1knaURZtM
            rmhjmcN+UOqsYFHMRSNCfiiUG2ESfGkVnzGMPm37gEGMbLg9hRsZGswtR4at4JKU
            dmGZCIj4jucjFF1yoXgluTxnI0fLb+NfMkVQyLQwKih66orluK07/frNLzkQh0z0
            Ta9RtJXX0VviGVE8UguuxElUESrCOLeQj81QVTe032NsclM5DE7V1EoWY1Zhw7u0
            ct+YwBUTKTD/UNc4LxAaortxWrNu3Uu8pNG+VukLAmvQi0ASwzYFc/Q2r03DYHDP
            IBG/lX01m1o1RF+8xVCxWsAsDpXUIXqlS+yE2EYCNXjNDngedzOKqZx79aQcIH6c
            fj5ENIV+8dj2fRn87gcYQYeQpHSB2x/fYQJ6jwb65CdAa/nCkFpQjRbhPZMcaCfv
            nyfX0VrQjvpftVjXceuANtWba/5INHbhHHutMgIgNVqV56bzyM2zXGEtY7yoPxCO
            nFwmqADjjwwMZyI05aQi9S/fjpW/ebPOIhIlbQAHKHmbLUVv/Rr7yv81/ji+aOQi
            3lW8W6TLHNjw4ef9F5oV72e8gVqPoj3HdkkMiwsElgjGzdYpUZNCKwZH85RK6Nk3
            F8U5kqoBtGwV5Xf6WVUTuL48D9myMLGWvnVJtVbBidku2c4AkH1K4SmPG0iV8YLS
            XgG1zXZIOkFLSdkGA0mAlawoTZZIaNfRdpsudyldM87HiL0wb3X/RhmEPz+Jo+Wp
            UXm1zFXO1FTtBf2HCDjoOWBWiMjRBgnu8LkdPLBaWUgCwk2mwk4n8naKdanQsq4=
            =is+6
            -----END PGP MESSAGE-----
          fp: EF57649CB133800963D136C6B813D6D7F00C2572
        - created_at: "2023-01-17T01:27:17Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAy4XleZm/m5jAQ/+MjNBGgfWQOqWYWeF2sRCVhBfbAKwH1KWjb72e6aa5d6H
            k02mtAGDEIlVDcair8FrG81u1LxODhKWKZpsU/YzCRonaOAl9F1m4XnXCkv+QcYO
            Q09ntXHkm8qm2bKjcEkIiBvMjv2tzSzz2H/DpzZ/JP8sgVUZKxKqfHPLRIZnBmDw
            UrdYeXUA1zwJJRigNIIFlmQL2ZKDiNxgx4vsGjYrdu8ShiB+4Uhlf7BPtR55OXQC
            Ptu28of8ZKibRXv40TIviLfGEYnYgtRtPrnspInz65itAAFu7TK3rMBTwLRK29ZE
            EqBx638/vy9QY+xooL5TK5p8Kmy25NGh9CBU85GR9koep26tWToacRHhkJlKGxkw
            Dn4OjF9LdXMhoS355v4R5FzNo1Jz4W7ItmREya5X2uLgj+hoU878PLVDSzvl57lI
            DphB0RX/TEqlVlupE97Zo/9sPjaNUN80cV+Z1e7PD3ZhxtgbzyBLU3Fd+W94nA2I
            kortv1DWghJCu2rU9VUEtCutIZS64eQw75caVo1o2rWWnsb/aA6ewco/xO6Hv1Fq
            oBkbBj7w1XGQYG86ZBHJ4KLlcUMTBM6RZj2iUy6mc13XxbsjmRE6JQrFgkK7+oOc
            fGB0Jddh+eLjH0UpR9TNJzCX9KPsdqXjfwkGLOOaPCKZ4+WymhwC+flQ8GtHku3S
            XgEx1eiKn5Mihh/dtRsbbaF23zKiL2v63kt71Cpxyt7EmDpxXNWWJYsnlzf0CZrK
            3eKKfMdgDyDZEMqB3jeOyZC//q/ZBZ6J6w4o1HsAHB/NxvugyVuTmtV7uMBUBlk=
            =6qCF
            -----END PGP MESSAGE-----
          fp: 0341B76EFD798D9008EE3A5B442753990A538576
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
