---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  METALLB_LB_RANGE: 192.168.1.210-192.168.1.229
  SVC_TRAEFIK_ADDR: 192.168.1.210
  NAS_ADDR: 192.168.1.33
  SVC_PLEX_ADDR: 192.168.1.210
  SVC_TRANSMISSION_ADDR: 192.168.1.210
