---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: sonarr
  namespace: media
spec:
  sourcePVC: sonarr-config-v1
  trigger:
    schedule: "02 11 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 10
    repository: sonarr-restic-secret
    cacheCapacity: 2Gi
    volumeSnapshotClassName: csi-ceph-blockpool
    storageClassName: ceph-block
    retain:
      daily: 10
      within: 3d
