---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-db-v1
  namespace: default
  labels:
    app.kubernetes.io/name: "mongodb"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block
---
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-nfs
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  storageClassName: mongodb-nfs
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: "wanshitong.${SECRET_DOMAIN}"
    path: /volume1/Backup/Mongodb
  mountOptions:
    - nconnect=8
    - noatime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-nfs
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: mongodb-nfs
  resources:
    requests:
      storage: 1Mi
