---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongodb
  namespace: default
spec:
  chart:
    spec:
      chart: mongodb
      version: 14.3.1
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  interval: 10m0s
  values:
    image:
      repository: bitnami/mongodb
      tag: 7.0.3-debian-11-r7
      pullPolicy: IfNotPresent
    strategy:
      type: Recreate
    architecture: standalone
    useStatefulSet: true
    clusterDomain: "${SECRET_DOMAIN}"
    auth:
      rootUser: root
      rootPassword: "${SECRET_MONGODB_PASSWORD}"
      usernames: ["${SECRET_MONGODB_UNIFI_USERNAME}", "${SECRET_MONGODB_UNIFI_USERNAME}"]
      passwords: ["${SECRET_MONGODB_UNIFI_PASSWORD}", "${SECRET_MONGODB_UNIFI_PASSWORD}"]
      databases: ["UNIFI", "UNIFI_stat"]
    persistence:
      enabled: true
      existingClaim: mongo-db-v1
    service:
      type: LoadBalancer
      loadBalancerIP: "${SVC_MONGODB_ADDR}"
    diagnosticMode: # All probes will be disabled and the command will be overridden with sleep infinity
      enabled: false
    backup:
      enabled: true
      cronjob:
        schedule: "@daily"
        storage:
          existingClaim: mongodb-nfs
    metrics:
      enabled: false
    resources:
      requests:
        memory: 100Mi
        cpu: 10m
      # limits:
      #   memory: 100Mi
      #   cpu: 100m