---
apiVersion: v1
kind: Secret
metadata:
  name: mymindinai-repo-creds
  namespace: flux-system
type: Opaque
stringData:
  identity: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
    NhAAAAAwEAAQAAAgEAo6InzR9n86Rhu/yx6oUvVdbqAFXLzKxLkIiVbeiowiQr0aM5WFXf
    XE+Pkucbw3sDbm8e2IFU81wfgMUP0TK02FGqFF+9TGZD3U7OZQgSc+kkA3zSZMLLESHIdL
    qJhLPCohhsIkS+eqFLg1hdjHmDsZmhL8sEiFIZsVbLX1JXJrosOdwoRRot9Jk6q23kHxOy
    WjA85RJpHDCGQn6izA3OL5Ru+2yLp7Lozw5MRScp1b7zJozJkE8YwOrtRZTyoh85oA9IgK
    O72ogxwf/fdo3615Ye3UW1cqKOR4A4cFOGSqEIGHMhge7k5sUffWqLCabqs443OUysDQUi
    9yFUD+xmHCEvkuTXL5hrypvf+vGRpWTym2H50geBA3yAXao2ipukvYEQO9lQpdAqN0W7+w
    g3DhaIVfL14SlR4MhUwON8ii2qGFzaaaGSFsYzZTTy8kQ0c7QT7uTGe1FlxC54iie/8oQ0
    oXKwtZEUchxpU3/dI9hBNrUnP0ha6hcjVusVbCvTkElUVzxSktIxDdaNa6dfmg60VhWZ1F
    7AS3An/YK/A6pqt8P6wNn80YNSsR/MDJ3vRLRyvDYINDTgKu8g0yYHorkZsp3KnnU5kk7F
    fWNh2xLfmwogKGBt6qikaNimSlJWU7OfGcr7Fgc8TaSnucmvquxPfJuKxkB70LcS126XhM
    cAAAdIwjX8NsI1/DYAAAAHc3NoLXJzYQAAAgEAo6InzR9n86Rhu/yx6oUvVdbqAFXLzKxL
    kIiVbeiowiQr0aM5WFXfXE+Pkucbw3sDbm8e2IFU81wfgMUP0TK02FGqFF+9TGZD3U7OZQ
    gSc+kkA3zSZMLLESHIdLqJhLPCohhsIkS+eqFLg1hdjHmDsZmhL8sEiFIZsVbLX1JXJros
    OdwoRRot9Jk6q23kHxOyWjA85RJpHDCGQn6izA3OL5Ru+2yLp7Lozw5MRScp1b7zJozJkE
    8YwOrtRZTyoh85oA9IgKO72ogxwf/fdo3615Ye3UW1cqKOR4A4cFOGSqEIGHMhge7k5sUf
    fWqLCabqs443OUysDQUi9yFUD+xmHCEvkuTXL5hrypvf+vGRpWTym2H50geBA3yAXao2ip
    ukvYEQO9lQpdAqN0W7+wg3DhaIVfL14SlR4MhUwON8ii2qGFzaaaGSFsYzZTTy8kQ0c7QT
    7uTGe1FlxC54iie/8oQ0oXKwtZEUchxpU3/dI9hBNrUnP0ha6hcjVusVbCvTkElUVzxSkt
    IxDdaNa6dfmg60VhWZ1F7AS3An/YK/A6pqt8P6wNn80YNSsR/MDJ3vRLRyvDYINDTgKu8g
    0yYHorkZsp3KnnU5kk7FfWNh2xLfmwogKGBt6qikaNimSlJWU7OfGcr7Fgc8TaSnucmvqu
    xPfJuKxkB70LcS126XhMcAAAADAQABAAACABiUcJ8e4xoVrLq01DLyy6/8xwzC1ojJrtYo
    ti2a39K95Tkp6CDNUW6H4vzBq4l7LoJFvd/u2Yhu46qPr3cQw1qlNcO2t/REflg9kMJbao
    4vzMGbW+1X13Ic3YQvSx38dLWtrnydT/GSzgmOWgsSa8ZfWfeYavdhQcvCSm1orH+8Qo10
    dTYgHxwZclcy/Cvw5P8oNNWCJPjfjyNo62J0hm7eQKeS4A2SUedccfeHUQDzHIpDZrm/L+
    w2veqQW7wfraPN9+me7sZ+Y98M5Q/ldvMwcTVy1bVBFtdFuvSgj1EhjFpD3Ror/QVvQfIw
    cW9DPAk5yTDZxBR2m5B82KhFrfa5Rbva5mKoOtX4DGjpfLCpP3Si4s1IWQG4QTTeCpwdAL
    /XVtRwIGVpODuFj8jAs5VhFquDdUGSROILiL73ryRu+lBY+0vuOeJLH3PClkQ2muN0xoiX
    lx4/ZxbY2U3dVyGdP8I473TCt37wezhVBzZSEJDiX291aXJh3u12KiT5Cu3LmtifwzzADw
    /ONOwVqbCv56bguPLZ7MlxPXV1Pzc+mcmDOWWIK4QvfKQOMjMk9UVDdM6VsVEtQhX+VHQX
    EUp0ZRybm3MjTeqhMpI87dwBzrak44D1Y70n5M+deuHVP4ZjtcmQNluD7ndvzWYoLO2MB0
    nzCEdkxHT82jbV5WxRAAABAQCuILG7adqrszBagHf7J5b4SqjZFJOhEYJWMSMOJx8Bjftb
    VvWZ+owEdx1xfoMMQ/pwCtdon39vPmGeunnXnKUuErFA4El7N6G/g/falKY9P+E0BYrX6Q
    s2GGgNJARppMpJnrKoZ8eRVTVmdEeN1LlJ4uIWEwU9TR7ntTVnBk3hNU7Q3EElDK7L9/9f
    R+7OtKLEStPlT0amGJN5PR5jkkUGsYF21xLBlSOq+bmfM9T9UNZvcT3mm4ZL8y93nhx6W5
    1Wv2JEZDpGV9mSJRoK4PQaPaTpF6CNbKmozkr09GcATBzQhLQKOoa2VQbtF149QYFuPERs
    KTo9I2RZCDO2D0+OAAABAQDLJaLah4kLaIr/Ru/K8P5K+rVsQRJ/Oym2OmRFrBjnIwNOof
    wgIwvHnBW4BsnjmRw1ENoe3ZSrcu9by8JKAeXV6Z+oOdF+dvlmVJYJPO1UCuqE+SnMlKFM
    I9H/d76O0PDVFqB7YwTP/MLsTKb198p9BZTIhjtajdJbr2LP6x5gBC712HRd7lT66MtcCA
    WAm/MrvreOqHkgFnPdlAmVZIL2xsjCv/Pbjmq8edT1X8ALwPjPWvQsQAftFA40HtibHJVo
    ry/TzBlaSi8cbXYDAc2ocateC79J4KFUIr5XOabaL5saDNyefcz6Pixavx4YjYgiSCyhlY
    ClPbn61A+BgjBxAAABAQDONMN3HsLJ4EfLCCKfXPj2/UwVR5Khwzqe+DsgFbuHUJHz82JS
    w6Va9ZVKlSIm4jRHRcYRULBBvKlAQVA994MKgy8KX3tMNey7r3VWb3zVqUE2cCVLYP0gOn
    aZdgfLMz5Dq6MmdS+csVcPSlRZ9KgT0Jzk4mUL0113usE55k/Yeg0SMj+26FSWSgtk9SHZ
    RvBYr3cRmkQQryMt+Dh00ZpcG9zhJIV3lZgEFDNtd/qt3V13y3HLc7bUbA79R/9drHV7mD
    an0q7mj5bP9tArT43mI7VALwr+es8lJ0ZNnFkyjePMzum9ILQxuW4PQpJDboSXvYnhONVK
    10YeyJYSpyS3AAAAEmpnaWxmb2lsQGdtYWlsLmNvbQ==
    -----END OPENSSH PRIVATE KEY-----
  known_hosts: |
    github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
    github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
    github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=

