apiVersion: v1
kind: Secret
metadata:
    name: mymindinai-repo-creds
    namespace: flux-system
type: Opaque
stringData:
    identity: ENC[AES256_GCM,data:HjXMhuvtjIUSaxzZBvaDhyG/xgAufMUIJoOHinZpHsRIocHdgXcVNyGYPUk10jMAl72SIVji/Y3VGF8n6vIHZHOz0u52R50sFaUj2GDryec+rwEWI+EUvtATz0wzm5fzvbdhNH8C//iP6h3BWCuCGVU8wASq80D/nsVOusMQOkj9dow0rGZCTMZepsr6lYMGD+rbqwRWcNFMLUKIeHGTJ7yEaoUjDlG1gIAnXa9IogVPPz70c2RJhtCNsGrgkWqd+Qxn8na57ZrfgJ3q4j4t6Fv0WR2riDziE3yYU3Q3Bn9LCsdy48DVsSmaaXBfNjrmNNe3tiRdJbVZdEsrz9ZOhOuTto5eWVTANU0mFigplr49HT6CUSG0AD86oxoVlr7KOfhbdRzD0qo/esCE7EJMzLfToyuqriEBbVGJV9yL3F1CMMI2zA1oKbbmnujGJHrKG1ew8/gfnj4Aij+J1MLSRFG55mvAMg/UfX8kx1AKunmuhXS6KbaxWcD1JrRMF+PdXiB7oR/weVipN/hU/6fUkuDUK5Hu5HCbdxy8,iv:BV9KEp/iVDQlwNb+c47IABNwlguue4wKp3JUZ7hhbtU=,tag:6Ml5YEkf26qr3ZO2dkgEdw==,type:str]
    known_hosts: ENC[AES256_GCM,data:civNkZ32BN3M59dmDh0hwmJWSwV7OqRji17+e/yFcBCJxkcT1AeKK2ZWFlkCERuOUJKRz1wMPuL7cCHtmqBCpY+WDFQ5kqoF28eCw2+WyHJCkm3PTUKxi/s6ChuInNQBgbC3LJz2yrP/pQZ6MkMLHdhWssUqbdeu7odqpIjK73UqMg7bt/Dil7JDkTb5YsEvPI5QnNUZ1rP02vcXWn7hSm2HEsTkbl+HEuXL4lWE+slEp1ZJcAFfojIGUhuu9Ef0Iore1f3myrcWdmgkbyot7bq0mIfIHNN1JhdcczeeO+/Zs8/Cm+DXsIC50vT7sdX4jM+ePG5SFzNlP5lOuvo8Cva7IwGzOfZsj9f3m+1cyArPruakJ64BH+/63y01gyyEKOtchPFw1JzJQEgCtzbPGTo1YkH808ovfYr6P/S0kheAC0QmfqChRBA7aJaKzTeJiPJPmWKh947nMvSjwr8+jSToYY6tbx3tWaUtET0XyRPtoIYaoYY6C0y0P0CLpHe3ihCKcjf667scUMwmpSDBeNQGHZKcfppsfmMkyZ0SMNcmbz87jivBiMKN1Hd4aRdwmZcMNbMsD5+v6AEvSX5+EUeXOngJ6ASbbHfkLgwoDBy+5Gc1USQr58h66jhXAOAZPxkK7XBskQn+RSo3rniVJ9c5yOrXZvxFQu/oOjFK5WR/FFx0WfShyZbBKz4krlqVlPnhHtZVQp6xJ4Esx2C4ERZ8jgJgqYrooEB3JINVkW4ERY4Q3hgHUA+gYsz3ph/GdZ+XCsl+ls0wqhVOFm0r+xiqQ5ZnhJOCSp5gkh3teHX1WLsHkijghREYqfG0AoIJ3U9IBwDJQXgCESzEs+IG4dNSdbQ8tgwkoOtirWeboOy4BTmp2VYgLCB4aU4+P3Ps8PCW70sZzQwo4p76b+3+7z1aXodLobAc/IwvT7emOvJFp7xFSo9Bb0/MWsJp5lYVW16lSQZ72+edYwiELT5v7KZy8Mw9HzkqMznGYpfmPk8OwSxUQSAXfZYtsTBmzqY8B1DVHQwI4+Zv/QDgNtIHZIFmzGavEzkXZvmIWzqTF4F0ktCkLpvukeLOKo7SVGSnTim8rCLeWSLJpStR,iv:DEQNeIc0lfJpSRPVt92Dw8mwDd1N3JfO5MQwhX1cmME=,tag:TVW5I2MW5yxmV61xJ0nusg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ktk92hs2qmfm8wnchvjve4z3wx60csm8g37mqj5gaw480x6mvemsn3rd4p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaeE9KT1NtdzgzbmhTM01m
            NFU2ZXlnL3FPSCtBclFSViticlZLUnN6S0VnCk5BTy9SZzFobTllRWJFeHhlWCtw
            T3MvRGZCc1pVb3orbTVoekgyWkxBYWsKLS0tIDBwMU44NFBFZDYxeTg3UjI3ODBJ
            ZFdqR2JFOWZoNGFtNG5mUHRwZDNxdzgKR0vAoZsWdEL25ybI10X9Pt4H4ZZcJvNF
            cI+B7EkwO3MgHkL2A0qytT3Onq2UXA2S90HU2tgPLaOHc3Z9xJKaTw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-17T21:43:19Z"
    mac: ENC[AES256_GCM,data:l9AjZxcA+YwihT8ULU51rSYSEcBTxb9RmutSkgUf+qg3ZrpiaxQeaZfCY8+YFIK6gtIrJ/V4eLb3FNDzRLl2pmLNdf4tHqxM7rDsRQEO1xf9lpsF+L0MvwT6JJFwvKo9L9h2nfeYx6Bwyl2TIgDYeDaMjznB2K1q24RvxfaRgKc=,iv:BOAsGNzwTahndzFSWAWdNCAf8kkho8bc0enUhjQ7Nmo=,tag:atKL8Qsk1pGhA7WfxtwKpg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
