---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vpn-gateway
  namespace: vpn-gateway
spec:
  interval: 5m
  chart:
    spec:
      chart: pod-gateway
      version: 5.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  # See https://github.com/k8s-at-home/charts/blob/master/charts/pod-gateway/values.yaml
  values:
    image:
      repository: ghcr.io/k8s-at-home/pod-gateway
      tag: v1.6.0
    addons:
      netshoot:
        enabled: true
      vpn:
        enabled: true
        type: wireguard
        wireguard:
          image:
            repository: ghcr.io/k8s-at-home/wireguard
            tag: v1.0.20210914
        env:
          TZ: "America/New_York"
          IPTABLES_BACKEND: legacy
          KILLSWITCH: "false"
        configFileSecret: vpn-gateway-vpnconfig
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            memory: 512Mi
        securityContext:
          runAsUser: 568
          runAsGroup: 568
          capabilities:
            drop:
              - "SYS_MODULE"
        networkPolicy:
          enabled: true
          egress:
            - to:
                - ipBlock:
                    cidr: 0.0.0.0/0
              ports:
                # VPN traffic
                - port: ${SECRET_VPN_GATEWAY_PORT}
                  protocol: UDP
            - to:
                - ipBlock:
                    cidr: 10.42.0.0/16
                - ipBlock:
                    cidr: 10.43.0.0/16
          initialDelaySeconds: 30
          periodSeconds: 90
          failureThreshold: 3
    routed_namespaces:
      - media
    DNS: 172.16.1.1
    settings:
      VPN_INTERFACE: wg0
      VXLAN_ID: 43
      VXLAN_IP_NETWORK: 172.16.1
      VPN_BLOCK_OTHER_TRAFFIC: true
      VPN_TRAFFIC_PORT: "${SECRET_VPN_GATEWAY_PORT}"
      NOT_ROUTED_TO_GATEWAY_CIDRS: "10.42.0.0/16 10.43.0.0/16 172.16.0.0/12 192.168.1.0/24"
      VPN_LOCAL_CIDRS: "172.16.0.0/12 10.42.0.0/16 10.43.0.0/16 192.168.1.0/24"
    publicPorts:
      - hostname: transmission
        IP: 10 # must be an integer between 2 and VXLAN_GATEWAY_FIRST_DYNAMIC_IP (20 by default)
        ports:
          - type: tcp
            port: 27071
          - type: udp
            port: 27071
    webhook:
      image:
        repository: ghcr.io/k8s-at-home/gateway-admision-controller
        tag: v3.4.0
      gatewayDefault: false
    #   gatewayLabel: setGateway
      gatewayAnnotation: setGateway
      namespaceSelector:
        label: "vpn-routed-gateway"
