---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vpn-gateway
  namespace: vpn-gateway
spec:
  interval: 5m
  chart:
    spec:
      chart: pod-gateway
      version: 5.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  # See https://github.com/k8s-at-home/charts/blob/master/charts/pod-gateway/values.yaml
  values:
    routed_namespaces:
      - media
    settings:
      # VPN_INTERFACE: wg0
      VPN_BLOCK_OTHER_TRAFFIC: true
      # VPN_TRAFFIC_PORT: "${VPN_GATEWAY_VPN_PORT}"
      NOT_ROUTED_TO_GATEWAY_CIDRS: "10.42.0.0/16 10.43.0.0/16"
      # VPN_LOCAL_CIDRS: "${NETWORK_K8S_CLUSTER_CIDR} ${NETWORK_K8S_SERVICE_CIDR} ${NETWORK_SERVER_CIDR}"
    image:
      repository: ghcr.io/k8s-at-home/pod-gateway
      tag: v1.4.0
    addons:
      vpn:
        enabled: true
        type: openvpn
        openvpn:
          image:
            repository: dperson/openvpn-client
            pullPolicy: Allways
            tag: latest

        configFileSecret: vpn-gateway-vpnconfig

        livenessProbe:
          exec:
            command:
              - sh
              - -c
              - if [ $(wget -q -O- http://ip-api.com/line/?fields=2) == 'NL' ]; then exit 0; else exit $?; fi
          initialDelaySeconds: 30
          periodSeconds: 90
          failureThreshold: 3

        networkPolicy:
          enabled: true
          egress:
            - to:
                - ipBlock:
                    cidr: 0.0.0.0/0
              ports:
                # VPN traffic
                - port: 443
                  protocol: UDP
            - to:
                - ipBlock:
                    cidr: 10.42.0.0/16
                - ipBlock:
                    cidr: 10.43.0.0/16

    publicPorts:
      - hostname: transmission
        IP: 10 # must be an integer between 2 and VXLAN_GATEWAY_FIRST_DYNAMIC_IP (20 by default)
        ports:
          - type: tcp
            port: 27071
          - type: udp
            port: 27071

    webhook:
      image:
        repository: ghcr.io/k8s-at-home/gateway-admision-controller
        tag: v3.4.0
      gatewayDefault: false
    #   gatewayLabel: setGateway
      gatewayAnnotation: setGateway
      namespaceSelector:
        label: "vpn-routed-gateway"
