---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-config-v1
  namespace: media
  labels:
    # kasten.io/backup-volume: "enabled"
    app.kubernetes.io/name: "transmission"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: ceph-block
