---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-downloads-v1
  namespace: media
  labels:
    app.kubernetes.io/name: "transmission"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ceph-block
