---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: transmission
  namespace: media
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://k8s-at-home.com/charts/
      chart: transmission
      version: 8.2.0
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/transmission
      tag: v3.00
      pullPolicy: IfNotPresent
    hostname: transmission
    env:
      TZ: "America/New_York"
      TRANSMISSION_RPC_PASSWORD: "${SECRET_TRANSMISSION_RPC_PASSWORD}"
      TRANSMISSION_DOWNLOAD_DIR: /downloads
    service:
      main:
        type: LoadBalancer
        externalIPs:
          - "${SVC_TRANSMISSION_ADDR}"
        externalTrafficPolicy: Local
        annotations:
          traefik.ingress.kubernetes.io/service.serversscheme: http
        ports:
          http:
            port: 9091
      utptcp:
        enabled: false
        type: ClusterIP
        ports:
          utptcp:
            enabled: true
            port: 51413
            protocol: TCP
            targetPort: 51413
      utpudp:
        enabled: false
        type: ClusterIP
        ports:
          utpudp:
            enabled: true
            port: 51413
            protocol: UDP
            targetPort: 51413
    ingress:
      main:
        enabled: true
        ingressClassName: "traefik"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          # hajimari.io/enable: "true"
          # hajimari.io/icon: "transmission"
          traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        hosts:
          - host: "transmission.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - "transmission.${SECRET_DOMAIN}"
            secretName: "transmission-tls"
    persistence:
      config:
        enabled: true
        existingClaim: transmission-config-v1
        mountPath: /config
      media:
        enabled: true
        type: custom
        volumeSpec:
          nfs:
            server: "${NAS_ADDR}"
            path: /volume2/Media/
        mountPath: /media
        readOnly: false
      downloads:
        enabled: true
        existingClaim: transmission-downloads-v1
        mountPath: /downloads
      watch:
        enabled: false
        mountPath: /watch
    podAnnotations:
      # backup.velero.io/backup-volumes: config
      setGateway: "true"
    probes:
      liveness:
        spec:
          timeoutSeconds: 30
      readiness:
        spec:
          timeoutSeconds: 30
    # initContainers:
    #   custom-webui:
    #     name: custom-webui
    #     image: curlimages/curl:7.76.1
    #     command:
    #       - "/bin/sh"
    #       - "-c"
    #       - "curl -o- -sL https://github.com/johman10/flood-for-transmission/releases/download/latest/flood-for-transmission.tar.gz | tar xzf - -C /config"
    #     volumeMounts:
    #       - name: config
    #         mountPath: /config
    #     securityContext:
    #       runAsUser: 568
    #       runAsGroup: 568
