---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: prowlarr
  namespace: default
spec:
  sourcePVC: prowlarr-config-v1
  trigger:
    schedule: "55 23 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 10
    repository: prowlarr-restic-secret
    cacheCapacity: 2Gi
    volumeSnapshotClassName: csi-ceph-blockpool
    storageClassName: ceph-block
    retain:
      daily: 10
      within: 3d
