# Thanks to eigenbahn.com/2020/04/15/ansible-synology for the initial code
- hosts: localhost
  tasks:

  - name: install sshpass
    apt:
      name: sshpass
      state: latest
    become: true

- hosts: synology
  remote_user: "{{ my_remote_user}}"
  gather_facts: False

  roles:
    - user