# Thanks to eigenbahn.com/2020/04/15/ansible-synology for the initial code
- hosts: localhost
  tasks:

  - name: install sshpass
    apt:
      name: sshpass
      state: latest
    become: true

- hosts: synology
  remote_user: "{{ my_remote_user }}"
  gather_facts: False
  roles:
    - user

- hosts: synology
  remote_user: "{{ my_ansible_username }}"
  gather_facts: False
  vars:
    ansible_ssh_pass: "{{ my_ansible_password }}"
    ansible_sudo_pass: "{{ my_ansible_password }}"
  roles:
    - minio_container