---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: overseerr
  namespace: media
spec:
  sourcePVC: overseerr-config-v1
  trigger:
    schedule: "00 11 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 10
    repository: overseerr-restic-secret
    cacheCapacity: 2Gi
    volumeSnapshotClassName: csi-ceph-blockpool
    storageClassName: ceph-block
    retain:
      daily: 10
      within: 3d
