---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://weaveworks.github.io/kured
      chart: kured
      version: 2.9.0
      sourceRef:
        kind: HelmRepository
        name: weaveworks-kured-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/k8s-at-home/kured
    updateStrategy: RollingUpdate
    configuration:
      timeZone: "America/New_York"
      startTime: "4:00"
      endTime: "10:00"
      # notifyUrl: "$_{SECRET_KURED_DISCORD_WEBHOOK}" # added _ to disable sops looking to replace that value for now.
      # messageTemplateDrain: "⏳ Draining node %s"
      # messageTemplateReboot: "♻️ Rebooted node %s"
      rebootCommand: "/usr/bin/systemctl reboot"
    tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
    # metrics:
    #   create: true
