---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kured
      version: 4.1.0
      sourceRef:
        kind: HelmRepository
        name: weaveworks-kured-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: ghcr.io/weaveworks/kured
    updateStrategy: RollingUpdate
    configuration:
      timeZone: "America/New_York"
      startTime: "4:00"
      endTime: "10:00"
      notifyUrl: "${SECRET_KURED_DISCORD_WEBHOOK}"
      messageTemplateDrain: "⏳ Draining node %s"
      messageTemplateReboot: "♻️ Rebooted node %s"
      rebootCommand: "/usr/bin/systemctl reboot"
    tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
    # metrics:
    #   create: true
