---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: "${SECRET_CLOUDDNS_EMAIL}"
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - dns01:
        cloudDNS:
          project: "${SECRET_CLOUDDNS_PROJECT}"
          serviceAccountSecretRef:
            name: clouddns-key-secret
            key: key.json
      selector:
        dnsZones:
          - ${SECRET_DOMAIN}
