---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: transmission
  namespace: media
spec:
  sourcePVC: transmission-config-v1
  trigger:
    schedule: "04 11 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 10
    repository: transmission-restic-secret
    cacheCapacity: 1Gi
    volumeSnapshotClassName: csi-ceph-blockpool
    storageClassName: ceph-block
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    retain:
      daily: 10
      within: 3d
