---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: transmission-downloads
  namespace: media
spec:
  sourcePVC: transmission-downloads-v1
  trigger:
    schedule: "05 11 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 10
    repository: transmission-downloads-restic-secret
    cacheCapacity: 5Gi
    volumeSnapshotClassName: csi-ceph-blockpool
    storageClassName: ceph-block
    retain:
      daily: 10
      within: 3d
