---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: velero
spec:
  interval: 5m
  chart:
    spec:
      chart: velero
      version: 2.32.6
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: velero/velero
      tag: v1.9.3
    configuration:
      extraEnvVars:
        TZ: "America/New_York"
      provider: aws
      backupStorageLocation:
        name: default
        bucket: k8sbackups
        config:
          region: us-east-1
          s3ForcePathStyle: true
          s3Url: http://${NAS_ADDR}:9000
          publicUrl: http://${NAS_ADDR}:9000
      volumeSnapshotLocation:
        name: aws
        config:
          region: us-east-1
      resticTimeout: 6h
      logLevel: debug
    initContainers:
      - name: velero-plugin-for-aws
        image: velero/velero-plugin-for-aws:v1.5.1@sha256:6e1817b6ad95c41182b24f2b373b1d9e6625c5e861b4d395e2dcde4bb9e2d547
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /target
            name: plugins
    credentials:
      existingSecret: velero-s3-creds
    schedules:
      daily-backup:
        schedule: "0 6 * * *"
        template:
          ttl: "120h"
    metrics:
      enabled: true
      # serviceMonitor:
      #   enabled: true
    snapshotsEnabled: true
    upgradeCRDs: false
    cleanUpCRDs: false
    kubectl:
      image:
        repository: ghcr.io/k8s-at-home/kubectl
        tag: v1.25.4
    deployRestic: true
    restic:
      podVolumePath: /var/lib/kubelet/pods
      privileged: false
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
      resources:
        requests:
          memory: 200Mi
          cpu: 15m
        limits:
          memory: 3000Mi
    resources:
      requests:
        memory: 300Mi
        cpu: 25m
      limits:
        memory: 1500Mi
