---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: mymindinaiapps
  namespace: mymindinai
spec:
  interval: 10m
  dependsOn:
    - name: apps
      namespace: flux-system
  targetNamespace: mymindinai
  sourceRef:
    kind: GitRepository
    name: mymindinai
  path: "./kubernetes/discordbot/overlays/prod"
  prune: true
  timeout: 1m
  patchesStrategicMerge:
    - patch.yaml
