---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mymind-discord-bot
  namespace: mymindinai
spec:
  template:
    spec:
      containers:
      - name: discord-bot
        env:
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: discordbot-config
              key: LOG_LEVEL
