---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mymind-bot
  namespace: mymindinai
spec:
  template:
    spec:
      containers:
      - name: mymind-bot
        env:
        - name: loglevel
          valueFrom:
            configMapKeyRef:
              name: discordbot-config
              key: LOG_LEVEL
