---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mymind-bot
spec:
  template:
    spec:
      volumes:
      - name: images
        persistentVolumeClaim:
          claimName: mymindinai-nfs