apiVersion: v1
kind: Secret
metadata:
    name: discordbot-secrets
    namespace: mymindinai
type: Opaque
data:
    DISCORD_BOT_TOKEN: ENC[AES256_GCM,data:0MbEDMOGoZFXHT1M9ElJAYN/5AINlLZFg1c0V1MVHA48lIrO3vVZK3z0Ex1zBS7HGcnb+ECaM2TEowv5Up3XxVtrXQZM+w5m,iv:fhi1/IH9Pa73BGbdJ4AJ+Jl/Nu0NgdCtnpQH9BcAFDE=,tag:0lZbExd/pMy4vmuK/VY/gw==,type:str]
    MIDJOURNEY_BOT_ID: ENC[AES256_GCM,data:5SciUB48+/aCNAx56GrHAWQr,iv:wqfgrkELj+tYGfwf4RMdXpZhdb8HTZWbnXeraXsS3VQ=,tag:WYyZYupbUGsuy65GIKqgnQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1ktk92hs2qmfm8wnchvjve4z3wx60csm8g37mqj5gaw480x6mvemsn3rd4p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYV3J2T1owYWwydTJOUWxN
            S1gvOW83U1lxZm9KK2xtZHh2a1liSERxSmlFCktuc2MzSGJVSE5sekw4c2VSczZ1
            dW9OUzJxZnRWUnYwemFlcDRYWGsyOFEKLS0tIHlTRVlnY3gva1VJd0dhU0lZZS9L
            eG9SMlZjWE1OUU1zN1c2WmQ1dGtaNEEKjRkRET4RT4i9PkoyFUHue9HGxJbzeOxV
            ZNeupzZDpAB7r5cLcOJsrA7h2Ma7zTmqTg+3/zTQwd/qVc5Xz6GHUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-05-17T21:44:13Z"
    mac: ENC[AES256_GCM,data:8WM30lYclIZKHZNLfQ3IlbxO2XUaVn3gmWqInMHV3IDC3d0kvWo+/RpRK4usNwPH0w7E4sM3P+Sl5zOmexr927lFpZehzO0r5d95AVmfDjA7vlpAy30TrebzB1axv/e0yC8f4DLSPx+f1HIplyl+HAeynV4cdVYA2Pim58cGgk8=,iv:o54Hs3jFwfcdXLFKoMySXdoiIpB9GxxdmIgtyFRFCy4=,tag:bTCRi2C5ypbSMJpek6xA1A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
