---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cleanup-downloads
  namespace: media
spec:
  schedule: "@daily"
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      backoffLimit: 3
      ttlSecondsAfterFinished: 300
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: findanddelete
              image: busybox
              command: ["/bin/sh"]
              args: ["-c", "find  /backups/containers/transmission/downloads-$(date +'%y-%m').tar -delete"]
              volumeMounts:
              - name: backups
                mountPath: /backups
          volumes:
          - name: backups
            nfs:
              server: "wanshitong.apostoli.pw"
              path: /volume1/Backup
